@startuml

   /'
     This file contains PlantUML source code to generate a UML diagram 
     that defines relationship between the main components of the 
     IPFIX YANG data model.

     Comments or questions about this Broadband Forum PlantUML file
     should be directed to <mailto:help@broadband-forum.org>.

     Editor:      Nick Hancock, ADTRAN

     Editor:      Ludwig Pauwels, Nokia

     PS Leader:   Joey Boyd, ADTRAN

     WA Director: Joey Boyd, ADTRAN

     WA Director: Sven Ooghe, Nokia";

     Copyright (c) 2023, Broadband Forum

     Redistribution and use in source and binary forms, with or
     without modification, are permitted provided that the following
     conditions are met:

     1. Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above
        copyright notice, this list of conditions and the following
        disclaimer in the documentation and/or other materials
        provided with the distribution.

     3. Neither the name of the copyright holder nor the names of its
        contributors may be used to endorse or promote products
        derived from this software without specific prior written
        permission.

     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
     CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES,
     INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
     MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
     CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
     SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
     NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
     CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
     ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
     ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

     The above license is used as a license under copyright only.
     Please reference the Forum IPR Policy for patent licensing terms
     <https://www.broadband-forum.org/ipr-policy>.

     Any moral rights which are necessary to exercise under the above
     license grant are also deemed granted under this license.

     This version of this PlantUML source code is part of TR-383a6; 
     see the TR itself for full legal notices.";

     revision 2023-06-21 {
       description
         "TBD.
          * Approval Date:    TBD.
          * Publication Date: TBD.";
       reference
         "TBD";
     }
  '/

  package "ietf-tls-client" {
  }
  
  package "bbf-ipfix-data-export" { 
    class "ipfix-data-export" <<container>> 
    class "exporting-process" <<list>>
    class "exporter" <<container>>
    class "destination" <<list>>
    class "security" <<container>>
    class "transport-session" <<container>>
    note right: config false
    class "template" as transport_session_template <<list>>
    class "options" <<list>>
    class "template" <<list>>
    hide members
    note right of transport_session_template : State data of templates used \nby an exporting process in a \nspecific transport session
    note bottom of template : Templates define the list of \ninformational elements to \nexport at the specified \nexport interval
  } 

  "bbf-ipfix-data-export" .up.> "ietf-tls-client" : <<import>>
  "ipfix-data-export" "1" *-- "0..*" "exporting-process" : \t
  "exporting-process" "1" *-- "0..*" "options"
  "exporting-process" "1" *-- "1..*" "destination"
  "destination" "1" *-- "1" "exporter"
  "exporter" "1" *-right- "1" "security" : \t
  "exporter" "1" *-- "1" "transport-session"
  "transport-session" "1" *-- "0..*" transport_session_template 
  "ipfix-data-export" "1" *-- "0..*" "template"
  "template" "0..*" -left-> "0..*" "exporting-process" : \t\t

@enduml