'Download plantuml from http://plantuml.sourceforge.net/ 
'Generate png with java -jar plantuml.jar <file> 
'Output in img/<module>.png 
'If Java spits out memory error increase heap size with java -Xmx1024m  -jar plantuml.jar <file> 
@startuml img/ietf-keystore_ietf-crypto-types.png 
hide empty fields 
hide empty methods 
hide <<case>> circle
hide <<augment>> circle
hide <<choice>> circle
hide <<leafref>> stereotype
hide <<leafref>> circle
page 1x1 
Title ietf-keystore_ietf-crypto-types 
package "nacm:ietf-netconf-acm" as nacm_ietf_netconf_acm { 
} 
package "ct:ietf-crypto-types" as ct_ietf_crypto_types { 
} 
package "ks:ietf-keystore" as ks_ietf_keystore { 
} 
note top of ks_ietf_keystore : <b>Namespace: </b> urn:ietf:params:xml:ns:yang:ietf-keystore \n<b>Prefix: </b> ks \n<b>Organization : </b>\nIETF NETCONF (Network Configuration) Working Group \n<b>Contact : </b>\nWG Web:   https://datatracker.ietf.org/wg/netconf \nWG List:  NETCONF WG list <mailto:netconf@ietf.org> \nAuthor:   Kent Watsen <mailto:kent+ietf@watsen.net> \n<b>Revision : </b> 2023-04-17 \n
package "ks:ietf-keystore" as ks_ietf_keystore { 
class "ietf-keystore" as ietf_keystore << (M, #33CCFF) module>> 
ietf_keystore : feature : central-keystore-supported 
ietf_keystore : feature : inline-definitions-supported 
ietf_keystore : feature : asymmetric-keys 
ietf_keystore : feature : symmetric-keys 
class "symmetric-key-ref" as ks_symmetric_key_ref_typedef << (T, YellowGreen) typedef>>
ks_symmetric_key_ref_typedef : leafref : /ks:keystore/ks:symmetric-keys/ks:symmetric-key/ks:name
class "asymmetric-key-ref" as ks_asymmetric_key_ref_typedef << (T, YellowGreen) typedef>>
ks_asymmetric_key_ref_typedef : leafref : /ks:keystore/ks:asymmetric-keys/ks:asymmetric-key/ks:name
class "encrypted-by-choice-grouping" as ietf_keystore_I_encrypted_by_choice_grouping_grouping <<(G,Lime) grouping>> 
class "encrypted-by-choice" as ietf_keystore_I_encrypted_by_choice_grouping_I_encrypted_by_choice <<choice>> 
ietf_keystore_I_encrypted_by_choice_grouping_grouping .. ietf_keystore_I_encrypted_by_choice_grouping_I_encrypted_by_choice : choice 
class "symmetric-key-ref" as ietf_keystore_I_encrypted_by_choice_grouping_I_encrypted_by_choice_I_symmetric_key_ref_case <<case>>
ietf_keystore_I_encrypted_by_choice_grouping_I_encrypted_by_choice .. ietf_keystore_I_encrypted_by_choice_grouping_I_encrypted_by_choice_I_symmetric_key_ref_case  : choice encrypted-by-choice
note bottom of ietf_keystore_I_encrypted_by_choice_grouping_I_encrypted_by_choice_I_symmetric_key_ref_case
<b>if-feature: </b>central-keystore-supported
end note 
note bottom of ietf_keystore_I_encrypted_by_choice_grouping_I_encrypted_by_choice_I_symmetric_key_ref_case
<b>if-feature: </b>symmetric-keys
end note 
ietf_keystore_I_encrypted_by_choice_grouping_I_encrypted_by_choice_I_symmetric_key_ref_case : symmetric-key-ref : ks:symmetric-key-ref  
class "asymmetric-key-ref" as ietf_keystore_I_encrypted_by_choice_grouping_I_encrypted_by_choice_I_asymmetric_key_ref_case <<case>>
ietf_keystore_I_encrypted_by_choice_grouping_I_encrypted_by_choice .. ietf_keystore_I_encrypted_by_choice_grouping_I_encrypted_by_choice_I_asymmetric_key_ref_case  : choice encrypted-by-choice
note bottom of ietf_keystore_I_encrypted_by_choice_grouping_I_encrypted_by_choice_I_asymmetric_key_ref_case
<b>if-feature: </b>central-keystore-supported
end note 
note bottom of ietf_keystore_I_encrypted_by_choice_grouping_I_encrypted_by_choice_I_asymmetric_key_ref_case
<b>if-feature: </b>asymmetric-keys
end note 
ietf_keystore_I_encrypted_by_choice_grouping_I_encrypted_by_choice_I_asymmetric_key_ref_case : asymmetric-key-ref : ks:asymmetric-key-ref  
class "asymmetric-key-certificate-ref-grouping" as ietf_keystore_I_asymmetric_key_certificate_ref_grouping_grouping <<(G,Lime) grouping>> 
ietf_keystore_I_asymmetric_key_certificate_ref_grouping_grouping : asymmetric-key : ks:asymmetric-key-ref   {if-feature : central-keystore-supported}
note bottom of ietf_keystore_I_asymmetric_key_certificate_ref_grouping_grouping
<b>Must</b> (asymmetric-key):
../certificate

end note 
ietf_keystore_I_asymmetric_key_certificate_ref_grouping_grouping : certificate : leafref : /ks:keystore/ks:asymmetric-keys/ks:asymmetric-key[ks:name = current{}/../asymmetric-key]/ks:certificates/ks:certificate/ks:name  
note bottom of ietf_keystore_I_asymmetric_key_certificate_ref_grouping_grouping
<b>Must</b> (certificate):
../asymmetric-key

end note 
class "inline-or-keystore-symmetric-key-grouping" as ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_grouping <<(G,Lime) grouping>> 
class "inline-or-keystore" as ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore <<choice>> 
ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_grouping .. ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore : choice 
class "inline" as ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore_I_inline_case <<case>>
ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore .. ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore_I_inline_case  : choice inline-or-keystore
note bottom of ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore_I_inline_case
<b>if-feature: </b>inline-definitions-supported
end note 
class "inline-definition" as  ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore_I_inline_I_inline_definition <<container>> 
ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore_I_inline_case *-- "1" ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore_I_inline_I_inline_definition 
ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore_I_inline_I_inline_definition : ct:symmetric-key-grouping {uses} 
class "keystore" as ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore_I_keystore_case <<case>>
ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore .. ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore_I_keystore_case  : choice inline-or-keystore
note bottom of ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore_I_keystore_case
<b>if-feature: </b>central-keystore-supported
end note 
note bottom of ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore_I_keystore_case
<b>if-feature: </b>symmetric-keys
end note 
ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore_I_keystore_case : keystore-reference : ks:symmetric-key-ref  
class "inline-or-keystore-asymmetric-key-grouping" as ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_grouping <<(G,Lime) grouping>> 
class "inline-or-keystore" as ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore <<choice>> 
ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_grouping .. ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore : choice 
class "inline" as ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore_I_inline_case <<case>>
ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore .. ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore_I_inline_case  : choice inline-or-keystore
note bottom of ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore_I_inline_case
<b>if-feature: </b>inline-definitions-supported
end note 
class "inline-definition" as  ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore_I_inline_I_inline_definition <<container>> 
ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore_I_inline_case *-- "1" ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore_I_inline_I_inline_definition 
ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore_I_inline_I_inline_definition : ct:asymmetric-key-pair-grouping {uses} 
class "keystore" as ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore_I_keystore_case <<case>>
ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore .. ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore_I_keystore_case  : choice inline-or-keystore
note bottom of ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore_I_keystore_case
<b>if-feature: </b>central-keystore-supported
end note 
note bottom of ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore_I_keystore_case
<b>if-feature: </b>asymmetric-keys
end note 
ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore_I_keystore_case : keystore-reference : ks:asymmetric-key-ref  
class "inline-or-keystore-asymmetric-key-with-certs-grouping" as ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_grouping <<(G,Lime) grouping>> 
class "inline-or-keystore" as ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore <<choice>> 
ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_grouping .. ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore : choice 
class "inline" as ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore_I_inline_case <<case>>
ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore .. ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore_I_inline_case  : choice inline-or-keystore
note bottom of ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore_I_inline_case
<b>if-feature: </b>inline-definitions-supported
end note 
class "inline-definition" as  ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore_I_inline_I_inline_definition <<container>> 
ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore_I_inline_case *-- "1" ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore_I_inline_I_inline_definition 
ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore_I_inline_I_inline_definition : ct:asymmetric-key-pair-with-certs-grouping {uses} 
class "keystore" as ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore_I_keystore_case <<case>>
ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore .. ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore_I_keystore_case  : choice inline-or-keystore
note bottom of ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore_I_keystore_case
<b>if-feature: </b>central-keystore-supported
end note 
note bottom of ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore_I_keystore_case
<b>if-feature: </b>asymmetric-keys
end note 
ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore_I_keystore_case : keystore-reference : ks:asymmetric-key-ref  
class "inline-or-keystore-end-entity-cert-with-key-grouping" as ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_grouping <<(G,Lime) grouping>> 
class "inline-or-keystore" as ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore <<choice>> 
ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_grouping .. ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore : choice 
class "inline" as ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_inline_case <<case>>
ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore .. ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_inline_case  : choice inline-or-keystore
note bottom of ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_inline_case
<b>if-feature: </b>inline-definitions-supported
end note 
class "inline-definition" as  ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_inline_I_inline_definition <<container>> 
ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_inline_case *-- "1" ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_inline_I_inline_definition 
ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_inline_I_inline_definition : ct:asymmetric-key-pair-with-cert-grouping {uses} 
class "keystore" as ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_keystore_case <<case>>
ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore .. ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_keystore_case  : choice inline-or-keystore
note bottom of ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_keystore_case
<b>if-feature: </b>central-keystore-supported
end note 
note bottom of ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_keystore_case
<b>if-feature: </b>asymmetric-keys
end note 
class "keystore-reference" as  ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_keystore_I_keystore_reference <<container>> 
ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_keystore_case *-- "1" ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_keystore_I_keystore_reference 
ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_keystore_I_keystore_reference : asymmetric-key-certificate-ref-grouping {uses} 
class "keystore-grouping" as ietf_keystore_I_keystore_grouping_grouping <<(G,Lime) grouping>> 
class "asymmetric-keys" as  ietf_keystore_I_keystore_grouping_I_asymmetric_keys <<container>> 
ietf_keystore_I_keystore_grouping_grouping *-- "1" ietf_keystore_I_keystore_grouping_I_asymmetric_keys 
note bottom of ietf_keystore_I_keystore_grouping_I_asymmetric_keys
<b>if-feature: </b>asymmetric-keys
end note 
class "asymmetric-key" as ietf_keystore_I_keystore_grouping_I_asymmetric_keys_I_asymmetric_key << (L, #FF7700) list>> 
ietf_keystore_I_keystore_grouping_I_asymmetric_keys *-- "0..N" ietf_keystore_I_keystore_grouping_I_asymmetric_keys_I_asymmetric_key 
ietf_keystore_I_keystore_grouping_I_asymmetric_keys_I_asymmetric_key : +name : string  {key} 
ietf_keystore_I_keystore_grouping_I_asymmetric_keys_I_asymmetric_key : ct:asymmetric-key-pair-with-certs-grouping {uses} 
class "symmetric-keys" as  ietf_keystore_I_keystore_grouping_I_symmetric_keys <<container>> 
ietf_keystore_I_keystore_grouping_grouping *-- "1" ietf_keystore_I_keystore_grouping_I_symmetric_keys 
note bottom of ietf_keystore_I_keystore_grouping_I_symmetric_keys
<b>if-feature: </b>symmetric-keys
end note 
class "symmetric-key" as ietf_keystore_I_keystore_grouping_I_symmetric_keys_I_symmetric_key << (L, #FF7700) list>> 
ietf_keystore_I_keystore_grouping_I_symmetric_keys *-- "0..N" ietf_keystore_I_keystore_grouping_I_symmetric_keys_I_symmetric_key 
ietf_keystore_I_keystore_grouping_I_symmetric_keys_I_symmetric_key : +name : string  {key} 
ietf_keystore_I_keystore_grouping_I_symmetric_keys_I_symmetric_key : ct:symmetric-key-grouping {uses} 
class "keystore" as  ietf_keystore_I_keystore <<container>> 
ietf_keystore *-- "1" ietf_keystore_I_keystore 
note bottom of ietf_keystore_I_keystore
<b>if-feature: </b>central-keystore-supported
end note 
ietf_keystore_I_keystore : keystore-grouping {uses} 
} 

nacm_ietf_netconf_acm +-- ks_ietf_keystore
ct_ietf_crypto_types +-- ks_ietf_keystore
package "yang:ietf-yang-types" as yang_ietf_yang_types { 
} 
package "nacm:ietf-netconf-acm" as nacm_ietf_netconf_acm { 
} 
package "ct:ietf-crypto-types" as ct_ietf_crypto_types { 
} 
note top of ct_ietf_crypto_types : <b>Namespace: </b> urn:ietf:params:xml:ns:yang:ietf-crypto-types \n<b>Prefix: </b> ct \n<b>Organization : </b>\nIETF NETCONF (Network Configuration) Working Group \n<b>Contact : </b>\nWG Web:   https://datatracker.ietf.org/wg/netconf \nWG List:  NETCONF WG list <mailto:netconf@ietf.org> \nAuthor:   Kent Watsen <mailto:kent+ietf@watsen.net> \n<b>Revision : </b> 2023-04-17 \n
package "ct:ietf-crypto-types" as ct_ietf_crypto_types { 
class "ietf-crypto-types" as ietf_crypto_types << (M, #33CCFF) module>> 
ietf_crypto_types : feature : one-symmetric-key-format 
ietf_crypto_types : feature : one-asymmetric-key-format 
ietf_crypto_types : feature : symmetrically-encrypted-value-format 
ietf_crypto_types : feature : asymmetrically-encrypted-value-format 
ietf_crypto_types : feature : cms-enveloped-data-format 
ietf_crypto_types : feature : cms-encrypted-data-format 
ietf_crypto_types : feature : p10-csr-format 
ietf_crypto_types : feature : csr-generation 
ietf_crypto_types : feature : certificate-expiration-notification 
ietf_crypto_types : feature : cleartext-passwords 
ietf_crypto_types : feature : encrypted-passwords 
ietf_crypto_types : feature : cleartext-symmetric-keys 
ietf_crypto_types : feature : hidden-symmetric-keys 
ietf_crypto_types : feature : encrypted-symmetric-keys 
ietf_crypto_types : feature : cleartext-private-keys 
ietf_crypto_types : feature : hidden-private-keys 
ietf_crypto_types : feature : encrypted-private-keys 
class "csr-info" as ct_csr_info_typedef << (T, YellowGreen) typedef>>
ct_csr_info_typedef : binary
class "p10-csr" as ct_p10_csr_typedef << (T, YellowGreen) typedef>>
ct_p10_csr_typedef : binary
class "x509" as ct_x509_typedef << (T, YellowGreen) typedef>>
ct_x509_typedef : binary
class "crl" as ct_crl_typedef << (T, YellowGreen) typedef>>
ct_crl_typedef : binary
class "oscp-request" as ct_oscp_request_typedef << (T, YellowGreen) typedef>>
ct_oscp_request_typedef : binary
class "oscp-response" as ct_oscp_response_typedef << (T, YellowGreen) typedef>>
ct_oscp_response_typedef : binary
class "cms" as ct_cms_typedef << (T, YellowGreen) typedef>>
ct_cms_typedef : binary
class "data-content-cms" as ct_data_content_cms_typedef << (T, YellowGreen) typedef>>
ct_data_content_cms_typedef : cms
class "signed-data-cms" as ct_signed_data_cms_typedef << (T, YellowGreen) typedef>>
ct_signed_data_cms_typedef : cms
class "enveloped-data-cms" as ct_enveloped_data_cms_typedef << (T, YellowGreen) typedef>>
ct_enveloped_data_cms_typedef : cms
class "digested-data-cms" as ct_digested_data_cms_typedef << (T, YellowGreen) typedef>>
ct_digested_data_cms_typedef : cms
class "encrypted-data-cms" as ct_encrypted_data_cms_typedef << (T, YellowGreen) typedef>>
ct_encrypted_data_cms_typedef : cms
class "authenticated-data-cms" as ct_authenticated_data_cms_typedef << (T, YellowGreen) typedef>>
ct_authenticated_data_cms_typedef : cms
class "trust-anchor-cert-x509" as ct_trust_anchor_cert_x509_typedef << (T, YellowGreen) typedef>>
ct_trust_anchor_cert_x509_typedef : x509
class "end-entity-cert-x509" as ct_end_entity_cert_x509_typedef << (T, YellowGreen) typedef>>
ct_end_entity_cert_x509_typedef : x509
class "trust-anchor-cert-cms" as ct_trust_anchor_cert_cms_typedef << (T, YellowGreen) typedef>>
ct_trust_anchor_cert_cms_typedef : signed-data-cms
class "end-entity-cert-cms" as ct_end_entity_cert_cms_typedef << (T, YellowGreen) typedef>>
ct_end_entity_cert_cms_typedef : signed-data-cms
class "encrypted-value-grouping" as ietf_crypto_types_I_encrypted_value_grouping_grouping <<(G,Lime) grouping>> 
class "encrypted-by" as  ietf_crypto_types_I_encrypted_value_grouping_I_encrypted_by <<container>> 
ietf_crypto_types_I_encrypted_value_grouping_grouping *-- "1" ietf_crypto_types_I_encrypted_value_grouping_I_encrypted_by 
ietf_crypto_types_I_encrypted_value_grouping_grouping : encrypted-value-format : identityref {encrypted-value-format}   {mandatory}
ietf_crypto_types_I_encrypted_value_grouping_grouping : encrypted-value : binary   {mandatory}
note bottom of ietf_crypto_types_I_encrypted_value_grouping_grouping
<b>Must</b> (encrypted-value):
../encrypted-by

end note 
class "password-grouping" as ietf_crypto_types_I_password_grouping_grouping <<(G,Lime) grouping>> 
class "password-type" as ietf_crypto_types_I_password_grouping_I_password_type <<choice>> 
ietf_crypto_types_I_password_grouping_grouping .. ietf_crypto_types_I_password_grouping_I_password_type : choice 
class "cleartext-password" as ietf_crypto_types_I_password_grouping_I_password_type_I_cleartext_password_case <<case>>
ietf_crypto_types_I_password_grouping_I_password_type .. ietf_crypto_types_I_password_grouping_I_password_type_I_cleartext_password_case  : choice password-type
note bottom of ietf_crypto_types_I_password_grouping_I_password_type_I_cleartext_password_case
<b>if-feature: </b>cleartext-passwords
end note 
ietf_crypto_types_I_password_grouping_I_password_type_I_cleartext_password_case : cleartext-password : string  
class "encrypted-password" as ietf_crypto_types_I_password_grouping_I_password_type_I_encrypted_password_case <<case>>
ietf_crypto_types_I_password_grouping_I_password_type .. ietf_crypto_types_I_password_grouping_I_password_type_I_encrypted_password_case  : choice password-type
note bottom of ietf_crypto_types_I_password_grouping_I_password_type_I_encrypted_password_case
<b>if-feature: </b>encrypted-passwords
end note 
class "encrypted-password" as  ietf_crypto_types_I_password_grouping_I_password_type_I_encrypted_password_I_encrypted_password <<container>> 
ietf_crypto_types_I_password_grouping_I_password_type_I_encrypted_password_case *-- "1" ietf_crypto_types_I_password_grouping_I_password_type_I_encrypted_password_I_encrypted_password 
ietf_crypto_types_I_password_grouping_I_password_type_I_encrypted_password_I_encrypted_password : encrypted-value-grouping {uses} 
class "symmetric-key-grouping" as ietf_crypto_types_I_symmetric_key_grouping_grouping <<(G,Lime) grouping>> 
ietf_crypto_types_I_symmetric_key_grouping_grouping : key-format : identityref {symmetric-key-format}  
class "key-type" as ietf_crypto_types_I_symmetric_key_grouping_I_key_type <<choice>> 
ietf_crypto_types_I_symmetric_key_grouping_grouping .. ietf_crypto_types_I_symmetric_key_grouping_I_key_type : choice 
class "cleartext-key" as ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_cleartext_key_case <<case>>
ietf_crypto_types_I_symmetric_key_grouping_I_key_type .. ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_cleartext_key_case  : choice key-type
ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_cleartext_key_case : cleartext-key : binary   {if-feature : cleartext-symmetric-keys}
note bottom of ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_cleartext_key_case
<b>Must</b> (cleartext-key):
../key-format

end note 
class "hidden-key" as ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_hidden_key_case <<case>>
ietf_crypto_types_I_symmetric_key_grouping_I_key_type .. ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_hidden_key_case  : choice key-type
note bottom of ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_hidden_key_case
<b>if-feature: </b>hidden-symmetric-keys
end note 
ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_hidden_key_case : hidden-key : empty  
note bottom of ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_hidden_key_case
<b>Must</b> (hidden-key):
not(../key-format)

end note 
class "encrypted-key" as ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_encrypted_key_case <<case>>
ietf_crypto_types_I_symmetric_key_grouping_I_key_type .. ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_encrypted_key_case  : choice key-type
note bottom of ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_encrypted_key_case
<b>if-feature: </b>encrypted-symmetric-keys
end note 
class "encrypted-key" as  ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_encrypted_key_I_encrypted_key <<container>> 
ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_encrypted_key_case *-- "1" ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_encrypted_key_I_encrypted_key 
note bottom of ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_encrypted_key_I_encrypted_key
<b>Must:</b>
../key-format
end note 
ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_encrypted_key_I_encrypted_key : encrypted-value-grouping {uses} 
class "public-key-grouping" as ietf_crypto_types_I_public_key_grouping_grouping <<(G,Lime) grouping>> 
ietf_crypto_types_I_public_key_grouping_grouping : public-key-format : identityref {public-key-format}   {mandatory}
ietf_crypto_types_I_public_key_grouping_grouping : public-key : binary   {mandatory}
class "asymmetric-key-pair-grouping" as ietf_crypto_types_I_asymmetric_key_pair_grouping_grouping <<(G,Lime) grouping>> 
ietf_crypto_types_I_asymmetric_key_pair_grouping_grouping : public-key-grouping {uses} 
ietf_crypto_types_I_asymmetric_key_pair_grouping_grouping : private-key-format : identityref {private-key-format}  
class "private-key-type" as ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type <<choice>> 
ietf_crypto_types_I_asymmetric_key_pair_grouping_grouping .. ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type : choice 
class "cleartext-private-key" as ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_cleartext_private_key_case <<case>>
ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type .. ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_cleartext_private_key_case  : choice private-key-type
note bottom of ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_cleartext_private_key_case
<b>if-feature: </b>cleartext-private-keys
end note 
ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_cleartext_private_key_case : cleartext-private-key : binary  
note bottom of ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_cleartext_private_key_case
<b>Must</b> (cleartext-private-key):
../private-key-format

end note 
class "hidden-private-key" as ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_hidden_private_key_case <<case>>
ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type .. ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_hidden_private_key_case  : choice private-key-type
note bottom of ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_hidden_private_key_case
<b>if-feature: </b>hidden-private-keys
end note 
ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_hidden_private_key_case : hidden-private-key : empty  
note bottom of ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_hidden_private_key_case
<b>Must</b> (hidden-private-key):
not(../private-key-format)

end note 
class "encrypted-private-key" as ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_encrypted_private_key_case <<case>>
ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type .. ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_encrypted_private_key_case  : choice private-key-type
note bottom of ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_encrypted_private_key_case
<b>if-feature: </b>encrypted-private-keys
end note 
class "encrypted-private-key" as  ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_encrypted_private_key_I_encrypted_private_key <<container>> 
ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_encrypted_private_key_case *-- "1" ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_encrypted_private_key_I_encrypted_private_key 
note bottom of ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_encrypted_private_key_I_encrypted_private_key
<b>Must:</b>
../private-key-format
end note 
ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_encrypted_private_key_I_encrypted_private_key : encrypted-value-grouping {uses} 
class "certificate-expiration-grouping" as ietf_crypto_types_I_certificate_expiration_grouping_grouping <<(G,Lime) grouping>> 
class "trust-anchor-cert-grouping" as ietf_crypto_types_I_trust_anchor_cert_grouping_grouping <<(G,Lime) grouping>> 
ietf_crypto_types_I_trust_anchor_cert_grouping_grouping : cert-data : trust-anchor-cert-cms  
ietf_crypto_types_I_trust_anchor_cert_grouping_grouping : certificate-expiration-grouping {uses} 
class "end-entity-cert-grouping" as ietf_crypto_types_I_end_entity_cert_grouping_grouping <<(G,Lime) grouping>> 
ietf_crypto_types_I_end_entity_cert_grouping_grouping : cert-data : end-entity-cert-cms  
ietf_crypto_types_I_end_entity_cert_grouping_grouping : certificate-expiration-grouping {uses} 
class "generate-csr-grouping" as ietf_crypto_types_I_generate_csr_grouping_grouping <<(G,Lime) grouping>> 
ietf_crypto_types_I_generate_csr_grouping_grouping : generate-csr( in: csr_format in: csr_info)
class "asymmetric-key-pair-with-cert-grouping" as ietf_crypto_types_I_asymmetric_key_pair_with_cert_grouping_grouping <<(G,Lime) grouping>> 
ietf_crypto_types_I_asymmetric_key_pair_with_cert_grouping_grouping : asymmetric-key-pair-grouping {uses} 
ietf_crypto_types_I_asymmetric_key_pair_with_cert_grouping_grouping : end-entity-cert-grouping {uses} 
ietf_crypto_types_I_asymmetric_key_pair_with_cert_grouping_grouping : generate-csr-grouping {uses} 
class "asymmetric-key-pair-with-certs-grouping" as ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_grouping <<(G,Lime) grouping>> 
ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_grouping : asymmetric-key-pair-grouping {uses} 
class "certificates" as  ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_I_certificates <<container>> 
ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_grouping *-- "1" ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_I_certificates 
class "certificate" as ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_I_certificates_I_certificate << (L, #FF7700) list>> 
ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_I_certificates *-- "0..N" ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_I_certificates_I_certificate 
ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_I_certificates_I_certificate : +name : string  {key} 
ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_I_certificates_I_certificate : end-entity-cert-grouping {uses} 
ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_grouping : generate-csr-grouping {uses} 
class "symmetric-key-format" as ct_symmetric_key_format_identity << (I,Silver) identity>> 
class "public-key-format" as ct_public_key_format_identity << (I,Silver) identity>> 
class "private-key-format" as ct_private_key_format_identity << (I,Silver) identity>> 
class "rsa-private-key-format" as ct_rsa_private_key_format_identity << (I,Silver) identity>> 
ct_private_key_format_identity <|-- ct_rsa_private_key_format_identity 
class "ec-private-key-format" as ct_ec_private_key_format_identity << (I,Silver) identity>> 
ct_private_key_format_identity <|-- ct_ec_private_key_format_identity 
class "one-asymmetric-key-format" as ct_one_asymmetric_key_format_identity << (I,Silver) identity>> 
ct_private_key_format_identity <|-- ct_one_asymmetric_key_format_identity 
class "ssh-public-key-format" as ct_ssh_public_key_format_identity << (I,Silver) identity>> 
ct_public_key_format_identity <|-- ct_ssh_public_key_format_identity 
class "subject-public-key-info-format" as ct_subject_public_key_info_format_identity << (I,Silver) identity>> 
ct_public_key_format_identity <|-- ct_subject_public_key_info_format_identity 
class "octet-string-key-format" as ct_octet_string_key_format_identity << (I,Silver) identity>> 
ct_symmetric_key_format_identity <|-- ct_octet_string_key_format_identity 
class "one-symmetric-key-format" as ct_one_symmetric_key_format_identity << (I,Silver) identity>> 
ct_symmetric_key_format_identity <|-- ct_one_symmetric_key_format_identity 
class "encrypted-value-format" as ct_encrypted_value_format_identity << (I,Silver) identity>> 
class "symmetrically-encrypted-value-format" as ct_symmetrically_encrypted_value_format_identity << (I,Silver) identity>> 
ct_encrypted_value_format_identity <|-- ct_symmetrically_encrypted_value_format_identity 
class "asymmetrically-encrypted-value-format" as ct_asymmetrically_encrypted_value_format_identity << (I,Silver) identity>> 
ct_encrypted_value_format_identity <|-- ct_asymmetrically_encrypted_value_format_identity 
class "cms-encrypted-data-format" as ct_cms_encrypted_data_format_identity << (I,Silver) identity>> 
ct_symmetrically_encrypted_value_format_identity <|-- ct_cms_encrypted_data_format_identity 
class "cms-enveloped-data-format" as ct_cms_enveloped_data_format_identity << (I,Silver) identity>> 
ct_asymmetrically_encrypted_value_format_identity <|-- ct_cms_enveloped_data_format_identity 
class "csr-format" as ct_csr_format_identity << (I,Silver) identity>> 
class "p10-csr-format" as ct_p10_csr_format_identity << (I,Silver) identity>> 
ct_csr_format_identity <|-- ct_p10_csr_format_identity 
ietf_crypto_types_I_encrypted_value_grouping_grouping-->ct_encrypted_value_format_identity : encrypted-value-format
ietf_crypto_types_I_symmetric_key_grouping_grouping-->ct_symmetric_key_format_identity : key-format
ietf_crypto_types_I_public_key_grouping_grouping-->ct_public_key_format_identity : public-key-format
ietf_crypto_types_I_asymmetric_key_pair_grouping_grouping-->ct_private_key_format_identity : private-key-format
} 

yang_ietf_yang_types +-- ct_ietf_crypto_types
nacm_ietf_netconf_acm +-- ct_ietf_crypto_types
ietf_keystore_I_inline_or_keystore_symmetric_key_grouping_I_inline_or_keystore_I_inline_I_inline_definition --> ietf_crypto_types_I_symmetric_key_grouping_grouping : uses 
ietf_keystore_I_inline_or_keystore_asymmetric_key_grouping_I_inline_or_keystore_I_inline_I_inline_definition --> ietf_crypto_types_I_asymmetric_key_pair_grouping_grouping : uses 
ietf_keystore_I_inline_or_keystore_asymmetric_key_with_certs_grouping_I_inline_or_keystore_I_inline_I_inline_definition --> ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_grouping : uses 
ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_inline_I_inline_definition --> ietf_crypto_types_I_asymmetric_key_pair_with_cert_grouping_grouping : uses 
ietf_keystore_I_inline_or_keystore_end_entity_cert_with_key_grouping_I_inline_or_keystore_I_keystore_I_keystore_reference --> ietf_keystore_I_asymmetric_key_certificate_ref_grouping_grouping : uses 
ietf_keystore_I_keystore_grouping_I_asymmetric_keys_I_asymmetric_key --> ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_grouping : uses 
ietf_keystore_I_keystore_grouping_I_symmetric_keys_I_symmetric_key --> ietf_crypto_types_I_symmetric_key_grouping_grouping : uses 
ietf_keystore_I_keystore --> ietf_keystore_I_keystore_grouping_grouping : uses 
ietf_crypto_types_I_password_grouping_I_password_type_I_encrypted_password_I_encrypted_password --> ietf_crypto_types_I_encrypted_value_grouping_grouping : uses 
ietf_crypto_types_I_symmetric_key_grouping_I_key_type_I_encrypted_key_I_encrypted_key --> ietf_crypto_types_I_encrypted_value_grouping_grouping : uses 
ietf_crypto_types_I_asymmetric_key_pair_grouping_grouping --> ietf_crypto_types_I_public_key_grouping_grouping : uses 
ietf_crypto_types_I_asymmetric_key_pair_grouping_I_private_key_type_I_encrypted_private_key_I_encrypted_private_key --> ietf_crypto_types_I_encrypted_value_grouping_grouping : uses 
ietf_crypto_types_I_trust_anchor_cert_grouping_grouping --> ietf_crypto_types_I_certificate_expiration_grouping_grouping : uses 
ietf_crypto_types_I_end_entity_cert_grouping_grouping --> ietf_crypto_types_I_certificate_expiration_grouping_grouping : uses 
ietf_crypto_types_I_asymmetric_key_pair_with_cert_grouping_grouping --> ietf_crypto_types_I_asymmetric_key_pair_grouping_grouping : uses 
ietf_crypto_types_I_asymmetric_key_pair_with_cert_grouping_grouping --> ietf_crypto_types_I_end_entity_cert_grouping_grouping : uses 
ietf_crypto_types_I_asymmetric_key_pair_with_cert_grouping_grouping --> ietf_crypto_types_I_generate_csr_grouping_grouping : uses 
ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_grouping --> ietf_crypto_types_I_asymmetric_key_pair_grouping_grouping : uses 
ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_I_certificates_I_certificate --> ietf_crypto_types_I_end_entity_cert_grouping_grouping : uses 
ietf_crypto_types_I_asymmetric_key_pair_with_certs_grouping_grouping --> ietf_crypto_types_I_generate_csr_grouping_grouping : uses 
ks_symmetric_key_ref_typedef-->"ks:name"ietf_keystore_I_keystore_I_symmetric_keys_I_symmetric_key: symmetric-key-ref
ks_asymmetric_key_ref_typedef-->"ks:name"ietf_keystore_I_keystore_I_asymmetric_keys_I_asymmetric_key: asymmetric-key-ref
center footer
 <size:20> UML Generated : 2023-07-19 14:45 </size>
 endfooter 
@enduml 
