'Download plantuml from http://plantuml.sourceforge.net/ 
'Generate png with java -jar plantuml.jar <file> 
'Output in img/<module>.png 
'If Java spits out memory error increase heap size with java -Xmx1024m  -jar plantuml.jar <file> 
@startuml img/bbf-l2-forwarding_bbf-l2-forward.png 
hide empty fields 
hide empty methods 
hide <<case>> circle
hide <<augment>> circle
hide <<choice>> circle
hide <<leafref>> stereotype
hide <<leafref>> circle
page 1x1 
Title bbf-l2-forwarding_bbf-l2-forward 
package "bbf-l2-fwd:bbf-l2-forwarding" as bbf_l2_fwd_bbf_l2_forwarding { 
} 
package "bbf-l2-fwd:bbf-l2-forwarding" as bbf_l2_fwd_bbf_l2_forwarding { 
package "bbf-l2-forwarding-base" as bbf_l2_forwarding_base { 
}
package "bbf-l2-forwarding-flooding-policies" as bbf_l2_forwarding_flooding_policies { 
}
package "bbf-l2-forwarding-forwarders" as bbf_l2_forwarding_forwarders { 
}
package "bbf-l2-forwarding-forwarding-databases" as bbf_l2_forwarding_forwarding_databases { 
}
package "bbf-l2-forwarding-mac-learning" as bbf_l2_forwarding_mac_learning { 
}
package "bbf-l2-forwarding-split-horizon-profiles" as bbf_l2_forwarding_split_horizon_profiles { 
}
package "bbf-l2-forwarding-mac-learning-control" as bbf_l2_forwarding_mac_learning_control { 
}
class "bbf-l2-forwarding" as bbf_l2_forwarding << (M, #33CCFF) module>> 
} 

package bbf-l2-forwarding {
package "bbf-l2-fwd:bbf-l2-forwarding-base" as bbf_l2_fwd_bbf_l2_forwarding_base { 
} 
package "bbf-l2-fwd:bbf-l2-forwarding-base" as bbf_l2_fwd_bbf_l2_forwarding_base { 
class "bbf-l2-forwarding-base" as bbf_l2_forwarding_base << (M, #33CCFF) module>> 
class "forwarding" as  bbf_l2_forwarding_base_I_forwarding <<container>> 
bbf_l2_forwarding_base *-- "1" bbf_l2_forwarding_base_I_forwarding 
class "forwarding-state" as  bbf_l2_forwarding_base_I_forwarding_state <<container>> 
bbf_l2_forwarding_base *-- "1" bbf_l2_forwarding_base_I_forwarding_state 
} 
} 

package "bbf-yang:bbf-yang-types" as bbf_yang_bbf_yang_types { 
} 
package "bbf-if-usg:bbf-interface-usage" as bbf_if_usg_bbf_interface_usage { 
} 
package "bbf-classif:bbf-frame-classification" as bbf_classif_bbf_frame_classification { 
} 
package bbf-l2-forwarding {
package "bbf-l2-fwd:bbf-l2-forwarding-flooding-policies" as bbf_l2_fwd_bbf_l2_forwarding_flooding_policies { 
} 
package "bbf-l2-fwd:bbf-l2-forwarding-flooding-policies" as bbf_l2_fwd_bbf_l2_forwarding_flooding_policies { 
package "bbf-l2-forwarding-base" as bbf_l2_forwarding_base { 
}
package "bbf-l2-forwarding-forwarders" as bbf_l2_forwarding_forwarders { 
}
class "bbf-l2-forwarding-flooding-policies" as bbf_l2_forwarding_flooding_policies << (M, #33CCFF) module>> 
bbf_l2_forwarding_flooding_policies : feature : flooding-policies 
bbf_l2_forwarding_flooding_policies : feature : flooding-policies-profiles 
class "/bbf-l2-fwd:forwarding" as bbf_l2_fwd_forwarding << (A,CadetBlue) augment>>
bbf_l2_forwarding_flooding_policies *--  bbf_l2_fwd_forwarding 
class "flooding-policies-profiles" as  bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles <<container>> 
bbf_l2_fwd_forwarding *-- "1" bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles 
class "flooding-policies-profile" as bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles *-- "0..N" bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile 
bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile : +name : bbf-yang:string-ascii64  {key} 
class "flooding-policy" as bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile *-- "0..N" bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy : ordered-by : user
bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy : +name : bbf-yang:string-ascii64  {key} 
class "in-interface-usages" as  bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_in_interface_usages <<container>> 
bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy *-- "1" bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_in_interface_usages 
bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_in_interface_usages : interface-usages []: bbf-if-usg:interface-usage 
class "destination-address" as  bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_destination_address <<container>> 
bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy *-- "1" bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_destination_address 
bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_destination_address : bbf-classif:frame-destination-match {uses} 
class "frame-forwarding" as bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_frame_forwarding <<choice>> 
bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy .. bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_frame_forwarding : choice 
class "discard" as bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_frame_forwarding_I_discard_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_frame_forwarding .. bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_frame_forwarding_I_discard_case  : choice frame-forwarding
bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_frame_forwarding_I_discard_case : discard : empty  
class "forward" as bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_frame_forwarding_I_forward_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_frame_forwarding .. bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_frame_forwarding_I_forward_case  : choice frame-forwarding
class "out-interface-usages" as  bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_frame_forwarding_I_forward_I_out_interface_usages <<container>> 
bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_frame_forwarding_I_forward_case *-- "1" bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_frame_forwarding_I_forward_I_out_interface_usages 
bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile_I_flooding_policy_I_frame_forwarding_I_forward_I_out_interface_usages : interface-usages []: bbf-if-usg:interface-usage 
class "/bbf-l2-fwd:forwarding/bbf-l2-fwd:forwarders/bbf-l2-fwd:forwarder" as bbf_l2_fwd_forwarding_bbf_l2_fwd_forwarders_bbf_l2_fwd_forwarder << (A,CadetBlue) augment>>
bbf_l2_forwarding_flooding_policies *--  bbf_l2_fwd_forwarding_bbf_l2_fwd_forwarders_bbf_l2_fwd_forwarder 
class "flooding-policies" as  bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies <<container>> 
bbf_l2_fwd_forwarding_bbf_l2_fwd_forwarders_bbf_l2_fwd_forwarder *-- "1" bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies 
class "flooding-policy-type" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type <<choice>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies .. bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type : choice 
class "profile-based" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_profile_based_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type .. bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_profile_based_case  : choice flooding-policy-type
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_profile_based_case : flooding-policies-profile : leafref : /bbf-l2-fwd:forwarding/bbf-l2-fwd:flooding-policies-profiles/bbf-l2-fwd:flooding-policies-profile/bbf-l2-fwd:name  
class "forwarder-specific" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type .. bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_case  : choice flooding-policy-type
class "flooding-policy" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_case *-- "0..N" bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy : ordered-by : user
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy : +name : bbf-yang:string-ascii64  {key} 
class "in-ports" as  bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_in_ports <<container>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy *-- "1" bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_in_ports 
class "list-type" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_in_ports_I_list_type <<choice>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_in_ports .. bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_in_ports_I_list_type : choice 
class "forwarder-port" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_in_ports_I_list_type_I_forwarder_port_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_in_ports_I_list_type .. bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_in_ports_I_list_type_I_forwarder_port_case  : choice list-type
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_in_ports_I_list_type_I_forwarder_port_case : forwarder-port : leafref : ../../../../bbf-l2-fwd:ports/bbf-l2-fwd:port/bbf-l2-fwd:name  
class "forwarder-port-group" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_in_ports_I_list_type_I_forwarder_port_group_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_in_ports_I_list_type .. bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_in_ports_I_list_type_I_forwarder_port_group_case  : choice list-type
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_in_ports_I_list_type_I_forwarder_port_group_case : forwarder-port-group : leafref : ../../../../bbf-l2-fwd:port-groups/bbf-l2-fwd:port-group/bbf-l2-fwd:name  
class "destination-address" as  bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_destination_address <<container>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy *-- "1" bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_destination_address 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_destination_address : bbf-classif:frame-destination-match {uses} 
class "frame-forwarding" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding <<choice>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy .. bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding : choice 
class "discard" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_discard_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding .. bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_discard_case  : choice frame-forwarding
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_discard_case : discard : empty  
class "forward" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding .. bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_case  : choice frame-forwarding
class "out-ports" as  bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_I_out_ports <<container>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_case *-- "1" bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_I_out_ports 
class "list-type" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_I_out_ports_I_list_type <<choice>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_I_out_ports .. bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_I_out_ports_I_list_type : choice 
class "forwarder-port" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_I_out_ports_I_list_type_I_forwarder_port_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_I_out_ports_I_list_type .. bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_I_out_ports_I_list_type_I_forwarder_port_case  : choice list-type
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_I_out_ports_I_list_type_I_forwarder_port_case : forwarder-port : leafref : ../../../../bbf-l2-fwd:ports/bbf-l2-fwd:port/bbf-l2-fwd:name  
class "forwarder-port-group" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_I_out_ports_I_list_type_I_forwarder_port_group_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_I_out_ports_I_list_type .. bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_I_out_ports_I_list_type_I_forwarder_port_group_case  : choice list-type
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_I_out_ports_I_list_type_I_forwarder_port_group_case : forwarder-port-group : leafref : ../../../../bbf-l2-fwd:port-groups/bbf-l2-fwd:port-group/bbf-l2-fwd:name  
} 
} 

bbf_yang_bbf_yang_types +-- bbf_l2_fwd_bbf_l2_forwarding_flooding_policies
bbf_if_usg_bbf_interface_usage +-- bbf_l2_fwd_bbf_l2_forwarding_flooding_policies
bbf_classif_bbf_frame_classification +-- bbf_l2_fwd_bbf_l2_forwarding_flooding_policies
package "bbf-yang:bbf-yang-types" as bbf_yang_bbf_yang_types { 
} 
package "bbfift:bbf-if-type" as bbfift_bbf_if_type { 
} 
package "if:ietf-interfaces" as if_ietf_interfaces { 
} 
package bbf-l2-forwarding {
package "bbf-l2-fwd:bbf-l2-forwarding-forwarders" as bbf_l2_fwd_bbf_l2_forwarding_forwarders { 
} 
package "bbf-l2-fwd:bbf-l2-forwarding-forwarders" as bbf_l2_fwd_bbf_l2_forwarding_forwarders { 
package "bbf-l2-forwarding-base" as bbf_l2_forwarding_base { 
}
class "bbf-l2-forwarding-forwarders" as bbf_l2_forwarding_forwarders << (M, #33CCFF) module>> 
bbf_l2_forwarding_forwarders : feature : forwarder-port-groups 
class "forwarder-ref" as bbf_l2_fwd_forwarder_ref_typedef << (T, YellowGreen) typedef>>
bbf_l2_fwd_forwarder_ref_typedef : leafref : /bbf-l2-fwd:forwarding/bbf-l2-fwd:forwarders/bbf-l2-fwd:forwarder/bbf-l2-fwd:name
class "forwarder-state-ref" as bbf_l2_fwd_forwarder_state_ref_typedef << (T, YellowGreen) typedef>>
bbf_l2_fwd_forwarder_state_ref_typedef : leafref : /bbf-l2-fwd:forwarding-state/bbf-l2-fwd:forwarders/bbf-l2-fwd:forwarder/bbf-l2-fwd:name
class "forwarder-port" as bbf_l2_forwarding_forwarders_I_forwarder_port_grouping <<(G,Lime) grouping>> 
bbf_l2_forwarding_forwarders_I_forwarder_port_grouping : forwarder : forwarder-ref  
bbf_l2_forwarding_forwarders_I_forwarder_port_grouping : port : leafref : /bbf-l2-fwd:forwarding/bbf-l2-fwd:forwarders/bbf-l2-fwd:forwarder[bbf-l2-fwd:name = current{}/../forwarder]/bbf-l2-fwd:ports/bbf-l2-fwd:port/bbf-l2-fwd:name  
class "forwarder-port-state" as bbf_l2_forwarding_forwarders_I_forwarder_port_state_grouping <<(G,Lime) grouping>> 
bbf_l2_forwarding_forwarders_I_forwarder_port_state_grouping : forwarder : forwarder-state-ref  
bbf_l2_forwarding_forwarders_I_forwarder_port_state_grouping : port : leafref : /bbf-l2-fwd:forwarding-state/bbf-l2-fwd:forwarders/bbf-l2-fwd:forwarder[bbf-l2-fwd:name = current{}/../forwarder]/bbf-l2-fwd:ports/bbf-l2-fwd:port/bbf-l2-fwd:name  
class "forwarder-port-group" as bbf_l2_forwarding_forwarders_I_forwarder_port_group_grouping <<(G,Lime) grouping>> 
bbf_l2_forwarding_forwarders_I_forwarder_port_group_grouping : forwarder : forwarder-ref  
bbf_l2_forwarding_forwarders_I_forwarder_port_group_grouping : group : leafref : /bbf-l2-fwd:forwarding/bbf-l2-fwd:forwarders/bbf-l2-fwd:forwarder[bbf-l2-fwd:name = current{}/../forwarder]/bbf-l2-fwd:port-groups/bbf-l2-fwd:port-group/bbf-l2-fwd:name  
class "/bbf-l2-fwd:forwarding" as bbf_l2_fwd_forwarding << (A,CadetBlue) augment>>
class "forwarders" as  bbf_l2_forwarding_base_I_forwarding_I_forwarders <<container>> 
bbf_l2_fwd_forwarding *-- "1" bbf_l2_forwarding_base_I_forwarding_I_forwarders 
class "forwarder" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarders *-- "0..N" bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder : +name : bbf-yang:string-ascii64  {key} 
class "ports" as  bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_ports <<container>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder *-- "1" bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_ports 
class "port" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_ports_I_port << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_ports *-- "0..N" bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_ports_I_port 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_ports_I_port : +name : bbf-yang:string-ascii64  {key} 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_ports_I_port : sub-interface : if:interface-ref  
class "port-groups" as  bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_port_groups <<container>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder *-- "1" bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_port_groups 
class "port-group" as bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_port_groups_I_port_group << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_port_groups *-- "0..N" bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_port_groups_I_port_group 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_port_groups_I_port_group : +name : bbf-yang:string-ascii64  {key} 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_port_groups_I_port_group : port []: leafref : ../../../bbf-l2-fwd:ports/bbf-l2-fwd:port/bbf-l2-fwd:name 
class "/bbf-l2-fwd:forwarding-state" as bbf_l2_fwd_forwarding_state << (A,CadetBlue) augment>>
bbf_l2_forwarding_forwarders *--  bbf_l2_fwd_forwarding_state 
class "forwarders" as  bbf_l2_forwarding_base_I_forwarding_state_I_forwarders <<container>> 
bbf_l2_fwd_forwarding_state *-- "1" bbf_l2_forwarding_base_I_forwarding_state_I_forwarders 
class "forwarder" as bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarders *-- "0..N" bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder : +name : bbf-yang:string-ascii64  {key} 
class "ports" as  bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder_I_ports <<container>> 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder *-- "1" bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder_I_ports 
class "port" as bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder_I_ports_I_port << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder_I_ports *-- "0..N" bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder_I_ports_I_port 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder_I_ports_I_port : +name : bbf-yang:string-ascii64  {key} 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder_I_ports_I_port : sub-interface : if:interface-state-ref  
} 
} 

bbf_yang_bbf_yang_types +-- bbf_l2_fwd_bbf_l2_forwarding_forwarders
bbfift_bbf_if_type +-- bbf_l2_fwd_bbf_l2_forwarding_forwarders
if_ietf_interfaces +-- bbf_l2_fwd_bbf_l2_forwarding_forwarders
package "bbf-yang:bbf-yang-types" as bbf_yang_bbf_yang_types { 
} 
package "yang:ietf-yang-types" as yang_ietf_yang_types { 
} 
package "if:ietf-interfaces" as if_ietf_interfaces { 
} 
package "bbfift:bbf-if-type" as bbfift_bbf_if_type { 
} 
package bbf-l2-forwarding {
package "bbf-l2-fwd:bbf-l2-forwarding-forwarding-databases" as bbf_l2_fwd_bbf_l2_forwarding_forwarding_databases { 
} 
package "bbf-l2-fwd:bbf-l2-forwarding-forwarding-databases" as bbf_l2_fwd_bbf_l2_forwarding_forwarding_databases { 
package "bbf-l2-forwarding-base" as bbf_l2_forwarding_base { 
}
package "bbf-l2-forwarding-forwarders" as bbf_l2_forwarding_forwarders { 
}
class "bbf-l2-forwarding-forwarding-databases" as bbf_l2_forwarding_forwarding_databases << (M, #33CCFF) module>> 
bbf_l2_forwarding_forwarding_databases : feature : forwarding-databases 
bbf_l2_forwarding_forwarding_databases : feature : shared-forwarding-databases 
bbf_l2_forwarding_forwarding_databases : feature : mac-learning 
bbf_l2_forwarding_forwarding_databases : feature : remaining-aging-time 
bbf_l2_forwarding_forwarding_databases : feature : clear-fdb-actions 
bbf_l2_forwarding_forwarding_databases : feature : interface-for-forwarding-database-port 
bbf_l2_forwarding_forwarding_databases : feature : read-system-fdb-capacity 
class "/bbf-l2-fwd:forwarding" as bbf_l2_fwd_forwarding << (A,CadetBlue) augment>>
class "forwarding-databases" as  bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases <<container>> 
bbf_l2_fwd_forwarding *-- "1" bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases 
class "forwarding-database" as bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases *-- "0..N" bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database : +name : bbf-yang:string-ascii64  {key} 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database : max-number-mac-addresses : uint32   = 4294967295 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database : aging-timer : uint32   = 300  {seconds} {if-feature : mac-learning}
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database : shared-forwarding-database : boolean   = false  {if-feature : shared-forwarding-databases}
class "static-mac-address" as bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database *-- "0..N" bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address : +mac-address : yang:mac-address  {key} 
class "learning-constraint" as bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint <<choice>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address .. bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint : choice 
class "do-not-learn-and-discard-frame" as bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_do_not_learn_and_discard_frame_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint .. bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_do_not_learn_and_discard_frame_case  : choice learning-constraint
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_do_not_learn_and_discard_frame_case : discard-frame : empty  
class "allowed-to-learn-on" as bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint .. bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_case  : choice learning-constraint
class "allow-to-learn-on" as bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on <<choice>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_case .. bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on : choice 
class "forwarder-port" as bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on_I_forwarder_port_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on .. bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on_I_forwarder_port_case  : choice allow-to-learn-on
class "forwarder-port-ref" as  bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on_I_forwarder_port_I_forwarder_port_ref <<container>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on_I_forwarder_port_case *-- "1" bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on_I_forwarder_port_I_forwarder_port_ref 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on_I_forwarder_port_I_forwarder_port_ref : forwarder-port {uses} 
class "forwarder-port-group" as bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on_I_forwarder_port_group_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on .. bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on_I_forwarder_port_group_case  : choice allow-to-learn-on
class "forwarder-port-group-ref" as  bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on_I_forwarder_port_group_I_forwarder_port_group_ref <<container>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on_I_forwarder_port_group_case *-- "1" bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on_I_forwarder_port_group_I_forwarder_port_group_ref 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on_I_forwarder_port_group_I_forwarder_port_group_ref : forwarder-port-group {uses} 
class "install-in-fdb-on" as bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_install_in_fdb_on_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint .. bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_install_in_fdb_on_case  : choice learning-constraint
class "install-on" as bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_install_in_fdb_on_I_install_on <<choice>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_install_in_fdb_on_case .. bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_install_in_fdb_on_I_install_on : choice 
class "static-port" as bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_install_in_fdb_on_I_install_on_I_static_port_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_install_in_fdb_on_I_install_on .. bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_install_in_fdb_on_I_install_on_I_static_port_case  : choice install-on
class "static-forwarder-port-ref" as  bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_install_in_fdb_on_I_install_on_I_static_port_I_static_forwarder_port_ref <<container>> 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_install_in_fdb_on_I_install_on_I_static_port_case *-- "1" bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_install_in_fdb_on_I_install_on_I_static_port_I_static_forwarder_port_ref 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_install_in_fdb_on_I_install_on_I_static_port_I_static_forwarder_port_ref : forwarder-port {uses} 
class "/bbf-l2-fwd:forwarding-state" as bbf_l2_fwd_forwarding_state << (A,CadetBlue) augment>>
class "forwarding-databases" as  bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases <<container>> 
bbf_l2_fwd_forwarding_state *-- "1" bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases : max-number-mac-addresses : uint32   {if-feature : read-system-fdb-capacity}
bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases : clear-mac-addresses()
class "forwarding-database" as bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases *-- "0..N" bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database : +name : bbf-yang:string-ascii64  {key} 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database : clear-mac-addresses()
class "mac-addresses" as  bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses <<container>> 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database *-- "1" bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses 
class "mac-address" as bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses_I_mac_address << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses *-- "0..N" bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses_I_mac_address 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses_I_mac_address : +mac-address : yang:mac-address  {key} 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses_I_mac_address : remaining-aging-time : uint32   {seconds} {if-feature : remaining-aging-time}
class "learned-on" as bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses_I_mac_address_I_learned_on <<choice>> 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses_I_mac_address .. bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses_I_mac_address_I_learned_on : choice 
class "forwarder-port" as bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses_I_mac_address_I_learned_on_I_forwarder_port_case <<case>>
bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses_I_mac_address_I_learned_on .. bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses_I_mac_address_I_learned_on_I_forwarder_port_case  : choice learned-on
bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses_I_mac_address_I_learned_on_I_forwarder_port_case : forwarder-port-state {uses} 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses_I_mac_address_I_learned_on_I_forwarder_port_case : sub-interface : if:interface-state-ref   {if-feature : interface-for-forwarding-database-port}
bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses_I_mac_address : clear-mac-address()
class "/bbf-l2-fwd:forwarding-state/bbf-l2-fwd:forwarders/bbf-l2-fwd:forwarder" as bbf_l2_fwd_forwarding_state_bbf_l2_fwd_forwarders_bbf_l2_fwd_forwarder << (A,CadetBlue) augment>>
bbf_l2_forwarding_forwarding_databases *--  bbf_l2_fwd_forwarding_state_bbf_l2_fwd_forwarders_bbf_l2_fwd_forwarder 
class "forwarding-databases" as  bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder_I_forwarding_databases <<container>> 
bbf_l2_fwd_forwarding_state_bbf_l2_fwd_forwarders_bbf_l2_fwd_forwarder *-- "1" bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder_I_forwarding_databases 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder_I_forwarding_databases : forwarding-database : leafref : /bbf-l2-fwd:forwarding-state/bbf-l2-fwd:forwarding-databases/bbf-l2-fwd:forwarding-database/bbf-l2-fwd:name  
} 
} 

bbf_yang_bbf_yang_types +-- bbf_l2_fwd_bbf_l2_forwarding_forwarding_databases
yang_ietf_yang_types +-- bbf_l2_fwd_bbf_l2_forwarding_forwarding_databases
if_ietf_interfaces +-- bbf_l2_fwd_bbf_l2_forwarding_forwarding_databases
bbfift_bbf_if_type +-- bbf_l2_fwd_bbf_l2_forwarding_forwarding_databases
package "ianaift:iana-if-type" as ianaift_iana_if_type { 
} 
package "bbfift:bbf-if-type" as bbfift_bbf_if_type { 
} 
package "if:ietf-interfaces" as if_ietf_interfaces { 
} 
package bbf-l2-forwarding {
package "bbf-l2-fwd:bbf-l2-forwarding-mac-learning" as bbf_l2_fwd_bbf_l2_forwarding_mac_learning { 
} 
package "bbf-l2-fwd:bbf-l2-forwarding-mac-learning" as bbf_l2_fwd_bbf_l2_forwarding_mac_learning { 
package "bbf-l2-forwarding-base" as bbf_l2_forwarding_base { 
}
package "bbf-l2-forwarding-forwarders" as bbf_l2_forwarding_forwarders { 
}
package "bbf-l2-forwarding-forwarding-databases" as bbf_l2_forwarding_forwarding_databases { 
}
class "bbf-l2-forwarding-mac-learning" as bbf_l2_forwarding_mac_learning << (M, #33CCFF) module>> 
class "/bbf-l2-fwd:forwarding/bbf-l2-fwd:forwarders/bbf-l2-fwd:forwarder" as bbf_l2_fwd_forwarding_bbf_l2_fwd_forwarders_bbf_l2_fwd_forwarder << (A,CadetBlue) augment>>
class "mac-learning" as  bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_mac_learning <<container>> 
bbf_l2_fwd_forwarding_bbf_l2_fwd_forwarders_bbf_l2_fwd_forwarder *-- "1" bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_mac_learning 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_mac_learning : forwarding-database : leafref : /bbf-l2-fwd:forwarding/bbf-l2-fwd:forwarding-databases/bbf-l2-fwd:forwarding-database/bbf-l2-fwd:name  
class "/if:interfaces/if:interface" as if_interfaces_if_interface << (A,CadetBlue) augment>>
bbf_l2_forwarding_mac_learning *--  if_interfaces_if_interface 
class "mac-learning" as  ietf_interfaces_I_interfaces_I_interface_I_mac_learning <<container>> 
if_interfaces_if_interface *-- "1" ietf_interfaces_I_interfaces_I_interface_I_mac_learning 
ietf_interfaces_I_interfaces_I_interface_I_mac_learning : max-number-mac-addresses : uint32   = 4294967295 
ietf_interfaces_I_interfaces_I_interface_I_mac_learning : number-committed-mac-addresses : uint32   = 1 
ietf_interfaces_I_interfaces_I_interface_I_mac_learning : mac-learning-enable : boolean   = true 
ietf_interfaces_I_interfaces_I_interface_I_mac_learning : mac-learning-failure-action : enumeration : {forward,discard,}   = forward 
} 
} 

ianaift_iana_if_type +-- bbf_l2_fwd_bbf_l2_forwarding_mac_learning
bbfift_bbf_if_type +-- bbf_l2_fwd_bbf_l2_forwarding_mac_learning
if_ietf_interfaces +-- bbf_l2_fwd_bbf_l2_forwarding_mac_learning
package "bbf-yang:bbf-yang-types" as bbf_yang_bbf_yang_types { 
} 
package "bbf-if-usg:bbf-interface-usage" as bbf_if_usg_bbf_interface_usage { 
} 
package bbf-l2-forwarding {
package "bbf-l2-fwd:bbf-l2-forwarding-mac-learning-control" as bbf_l2_fwd_bbf_l2_forwarding_mac_learning_control { 
} 
package "bbf-l2-fwd:bbf-l2-forwarding-mac-learning-control" as bbf_l2_fwd_bbf_l2_forwarding_mac_learning_control { 
package "bbf-l2-forwarding-base" as bbf_l2_forwarding_base { 
}
package "bbf-l2-forwarding-forwarders" as bbf_l2_forwarding_forwarders { 
}
package "bbf-l2-forwarding-forwarding-databases" as bbf_l2_forwarding_forwarding_databases { 
}
class "bbf-l2-forwarding-mac-learning-control" as bbf_l2_forwarding_mac_learning_control << (M, #33CCFF) module>> 
bbf_l2_forwarding_mac_learning_control : feature : mac-learning-control-profiles 
class "/bbf-l2-fwd:forwarding" as bbf_l2_fwd_forwarding << (A,CadetBlue) augment>>
class "mac-learning-control-profiles" as  bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles <<container>> 
bbf_l2_fwd_forwarding *-- "1" bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles 
class "mac-learning-control-profile" as bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles *-- "0..N" bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile 
bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile : +name : bbf-yang:string-ascii64  {key} 
class "mac-learning-rule" as bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile_I_mac_learning_rule << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile *-- "0..N" bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile_I_mac_learning_rule 
bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile_I_mac_learning_rule : +receiving-interface-usage : bbf-if-usg:interface-usage  {key} 
class "mac-learning-action" as bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile_I_mac_learning_rule_I_mac_learning_action <<choice>> 
bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile_I_mac_learning_rule .. bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile_I_mac_learning_rule_I_mac_learning_action : choice 
class "learn-and-translate" as bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile_I_mac_learning_rule_I_mac_learning_action_I_learn_and_translate_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile_I_mac_learning_rule_I_mac_learning_action .. bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile_I_mac_learning_rule_I_mac_learning_action_I_learn_and_translate_case  : choice mac-learning-action
class "learn-but-do-not-move" as bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile_I_mac_learning_rule_I_mac_learning_action_I_learn_but_do_not_move_case <<case>>
bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile_I_mac_learning_rule_I_mac_learning_action .. bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile_I_mac_learning_rule_I_mac_learning_action_I_learn_but_do_not_move_case  : choice mac-learning-action
bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile_I_mac_learning_rule_I_mac_learning_action_I_learn_but_do_not_move_case : mac-can-not-move-to []: bbf-if-usg:interface-usage 
class "/bbf-l2-fwd:forwarding/bbf-l2-fwd:forwarding-databases/bbf-l2-fwd:forwarding-database" as bbf_l2_fwd_forwarding_bbf_l2_fwd_forwarding_databases_bbf_l2_fwd_forwarding_database << (A,CadetBlue) augment>>
bbf_l2_forwarding_mac_learning_control *--  bbf_l2_fwd_forwarding_bbf_l2_fwd_forwarding_databases_bbf_l2_fwd_forwarding_database 
class "mac-learning-control" as  bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_mac_learning_control <<container>> 
bbf_l2_fwd_forwarding_bbf_l2_fwd_forwarding_databases_bbf_l2_fwd_forwarding_database *-- "1" bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_mac_learning_control 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_mac_learning_control : mac-learning-control-profile : leafref : /bbf-l2-fwd:forwarding/bbf-l2-fwd:mac-learning-control-profiles/bbf-l2-fwd:mac-learning-control-profile/bbf-l2-fwd:name  
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_mac_learning_control : generate-mac-learning-alarm : boolean   = false 
} 
} 

bbf_yang_bbf_yang_types +-- bbf_l2_fwd_bbf_l2_forwarding_mac_learning_control
bbf_if_usg_bbf_interface_usage +-- bbf_l2_fwd_bbf_l2_forwarding_mac_learning_control
package "bbf-yang:bbf-yang-types" as bbf_yang_bbf_yang_types { 
} 
package "bbf-if-usg:bbf-interface-usage" as bbf_if_usg_bbf_interface_usage { 
} 
package bbf-l2-forwarding {
package "bbf-l2-fwd:bbf-l2-forwarding-split-horizon-profiles" as bbf_l2_fwd_bbf_l2_forwarding_split_horizon_profiles { 
} 
package "bbf-l2-fwd:bbf-l2-forwarding-split-horizon-profiles" as bbf_l2_fwd_bbf_l2_forwarding_split_horizon_profiles { 
package "bbf-l2-forwarding-base" as bbf_l2_forwarding_base { 
}
package "bbf-l2-forwarding-forwarders" as bbf_l2_forwarding_forwarders { 
}
class "bbf-l2-forwarding-split-horizon-profiles" as bbf_l2_forwarding_split_horizon_profiles << (M, #33CCFF) module>> 
bbf_l2_forwarding_split_horizon_profiles : feature : split-horizon-profiles 
class "/bbf-l2-fwd:forwarding" as bbf_l2_fwd_forwarding << (A,CadetBlue) augment>>
class "split-horizon-profiles" as  bbf_l2_forwarding_base_I_forwarding_I_split_horizon_profiles <<container>> 
bbf_l2_fwd_forwarding *-- "1" bbf_l2_forwarding_base_I_forwarding_I_split_horizon_profiles 
class "split-horizon-profile" as bbf_l2_forwarding_base_I_forwarding_I_split_horizon_profiles_I_split_horizon_profile << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_I_split_horizon_profiles *-- "0..N" bbf_l2_forwarding_base_I_forwarding_I_split_horizon_profiles_I_split_horizon_profile 
bbf_l2_forwarding_base_I_forwarding_I_split_horizon_profiles_I_split_horizon_profile : +name : bbf-yang:string-ascii64  {key} 
class "split-horizon" as bbf_l2_forwarding_base_I_forwarding_I_split_horizon_profiles_I_split_horizon_profile_I_split_horizon << (L, #FF7700) list>> 
bbf_l2_forwarding_base_I_forwarding_I_split_horizon_profiles_I_split_horizon_profile *-- "0..N" bbf_l2_forwarding_base_I_forwarding_I_split_horizon_profiles_I_split_horizon_profile_I_split_horizon 
bbf_l2_forwarding_base_I_forwarding_I_split_horizon_profiles_I_split_horizon_profile_I_split_horizon : +in-interface-usage : bbf-if-usg:interface-usage  {key} 
bbf_l2_forwarding_base_I_forwarding_I_split_horizon_profiles_I_split_horizon_profile_I_split_horizon : out-interface-usage []: bbf-if-usg:interface-usage 
class "/bbf-l2-fwd:forwarding/bbf-l2-fwd:forwarders/bbf-l2-fwd:forwarder" as bbf_l2_fwd_forwarding_bbf_l2_fwd_forwarders_bbf_l2_fwd_forwarder << (A,CadetBlue) augment>>
class "split-horizon-profiles" as  bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_split_horizon_profiles <<container>> 
bbf_l2_fwd_forwarding_bbf_l2_fwd_forwarders_bbf_l2_fwd_forwarder *-- "1" bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_split_horizon_profiles 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_split_horizon_profiles : split-horizon-profile : leafref : /bbf-l2-fwd:forwarding/bbf-l2-fwd:split-horizon-profiles/bbf-l2-fwd:split-horizon-profile/bbf-l2-fwd:name  
} 
} 

bbf_yang_bbf_yang_types +-- bbf_l2_fwd_bbf_l2_forwarding_split_horizon_profiles
bbf_if_usg_bbf_interface_usage +-- bbf_l2_fwd_bbf_l2_forwarding_split_horizon_profiles
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on_I_forwarder_port_I_forwarder_port_ref --> bbf_l2_forwarding_forwarders_I_forwarder_port_grouping : uses 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_allowed_to_learn_on_I_allow_to_learn_on_I_forwarder_port_group_I_forwarder_port_group_ref --> bbf_l2_forwarding_forwarders_I_forwarder_port_group_grouping : uses 
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_static_mac_address_I_learning_constraint_I_install_in_fdb_on_I_install_on_I_static_port_I_static_forwarder_port_ref --> bbf_l2_forwarding_forwarders_I_forwarder_port_grouping : uses 
bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database_I_mac_addresses_I_mac_address_I_learned_on_I_forwarder_port_case --> bbf_l2_forwarding_forwarders_I_forwarder_port_state_grouping : uses 
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_profile_based_case-->"bbf-l2-fwd:name"bbf_l2_forwarding_base_I_forwarding_I_flooding_policies_profiles_I_flooding_policies_profile: flooding-policies-profile
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_in_ports_I_list_type_I_forwarder_port_case-->"bbf-l2-fwd:name"bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_ports_I_port: forwarder-port
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_in_ports_I_list_type_I_forwarder_port_group_case-->"bbf-l2-fwd:name"bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_port_groups_I_port_group: forwarder-port-group
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_I_out_ports_I_list_type_I_forwarder_port_case-->"bbf-l2-fwd:name"bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_ports_I_port: forwarder-port
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_flooding_policies_I_flooding_policy_type_I_forwarder_specific_I_flooding_policy_I_frame_forwarding_I_forward_I_out_ports_I_list_type_I_forwarder_port_group_case-->"bbf-l2-fwd:name"bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_port_groups_I_port_group: forwarder-port-group
bbf_l2_fwd_forwarder_ref_typedef-->"bbf-l2-fwd:name"bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder: forwarder-ref
bbf_l2_fwd_forwarder_state_ref_typedef-->"bbf-l2-fwd:name"bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder: forwarder-state-ref
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_port_groups_I_port_group-->"bbf-l2-fwd:name"bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_ports_I_port: port
bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder_I_forwarding_databases-->"bbf-l2-fwd:name"bbf_l2_forwarding_base_I_forwarding_state_I_forwarding_databases_I_forwarding_database: forwarding-database
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_mac_learning-->"bbf-l2-fwd:name"bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database: forwarding-database
bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database_I_mac_learning_control-->"bbf-l2-fwd:name"bbf_l2_forwarding_base_I_forwarding_I_mac_learning_control_profiles_I_mac_learning_control_profile: mac-learning-control-profile
bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder_I_split_horizon_profiles-->"bbf-l2-fwd:name"bbf_l2_forwarding_base_I_forwarding_I_split_horizon_profiles_I_split_horizon_profile: split-horizon-profile
bbf_l2_fwd_forwarding_bbf_l2_fwd_forwarders_bbf_l2_fwd_forwarder-->bbf_l2_forwarding_base_I_forwarding_I_forwarders_I_forwarder : augments
bbf_l2_fwd_forwarding_bbf_l2_fwd_forwarding_databases_bbf_l2_fwd_forwarding_database-->bbf_l2_forwarding_base_I_forwarding_I_forwarding_databases_I_forwarding_database : augments
bbf_l2_fwd_forwarding_state_bbf_l2_fwd_forwarders_bbf_l2_fwd_forwarder-->bbf_l2_forwarding_base_I_forwarding_state_I_forwarders_I_forwarder : augments
bbf_l2_fwd_forwarding_state-->bbf_l2_forwarding_base_I_forwarding_state : augments
bbf_l2_fwd_forwarding-->bbf_l2_forwarding_base_I_forwarding : augments
center footer
 <size:20> UML Generated : 2023-07-25 11:28 </size>
 endfooter 
@enduml 
