@startuml
'comment: ONU Software Download
skinparam maxMessageSize 200
participant "ONU"
participant "vOLTMF"
participant "vOMCIFunction"
participant "Access_SDN_M_C"

"Access_SDN_M_C" -> "vOLTMF": 1)Update ONU\nsoftware image\n(URI or filename)
"vOLTMF" -> "vOMCIFunction": 2)Update ONU\nsoftware image\n(URI or filename)
group 3)Image transfer\nfrom clause 9.1.4
"vOMCIFunction" -> "ONU": 3a)Start download
"ONU" -> "vOMCIFunction": Start download response
"vOMCIFunction" -> "ONU": 3b)Download section
"vOMCIFunction" -> "ONU": 3b)Download section
"ONU" -> "vOMCIFunction": 3b)Download section response\na single response per\nwindow-size requests
"vOMCIFunction" --> "ONU": <font color=red>Unrelated request X
"ONU" --> "vOMCIFunction": <font color=red>request X response
"vOMCIFunction" -> "ONU": 3b)Download section
"vOMCIFunction" -> "ONU": 3b)Download section
"ONU" -> "vOMCIFunction": 3b)Download section response
"vOMCIFunction" -> "ONU": 3c)End download
"ONU" -> "vOMCIFunction": End download response
end
"vOMCIFunction" -> "vOLTMF": 4) software-downloaded
"vOLTMF" -> "Access_SDN_M_C": 5)software-downloaded

@enduml
