'Download plantuml from http://plantuml.sourceforge.net/ 
'Generate png with java -jar plantuml.jar <file> 
'Output in img/<module>.png 
'If Java spits out memory error increase heap size with java -Xmx1024m  -jar plantuml.jar <file> 
@startuml img/bbf-ipfix-data-export.png 
hide empty fields 
hide empty methods 
hide <<case>> circle
hide <<augment>> circle
hide <<choice>> circle
hide <<leafref>> stereotype
hide <<leafref>> circle
page 1x1 
Title bbf-ipfix-data-export 
package "bbf-yang:bbf-yang-types" as bbf_yang_bbf_yang_types { 
} 
package "inet:ietf-inet-types" as inet_ietf_inet_types { 
} 
package "yang:ietf-yang-types" as yang_ietf_yang_types { 
} 
package "if:ietf-interfaces" as if_ietf_interfaces { 
} 
package "tlsc:ietf-tls-client" as tlsc_ietf_tls_client { 
} 
package "bbf-ipfix-de:bbf-ipfix-data-export" as bbf_ipfix_de_bbf_ipfix_data_export { 
} 
package "bbf-ipfix-de:bbf-ipfix-data-export" as bbf_ipfix_de_bbf_ipfix_data_export { 
class "bbf-ipfix-data-export" as bbf_ipfix_data_export << (M, #33CCFF) module>> 
bbf_ipfix_data_export : feature : exporter 
class "ie-id-type" as bbf_ipfix_de_ie_id_type_typedef << (T, YellowGreen) typedef>>
bbf_ipfix_de_ie_id_type_typedef : uint16 [1..32767]
enum "transport-session-status" as bbf_ipfix_de_transport_session_status_typedef <<enumeration>> {
inactive
active
unknown
}
class "resource" as bbf_ipfix_de_resource_typedef << (T, YellowGreen) typedef>>
bbf_ipfix_de_resource_typedef : instance-identifier
class "ipfix-data-export" as  bbf_ipfix_data_export_I_ipfix_data_export <<container>> 
bbf_ipfix_data_export *-- "1" bbf_ipfix_data_export_I_ipfix_data_export 
class "exporting-process" as bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process << (L, #FF7700) list>> 
bbf_ipfix_data_export_I_ipfix_data_export *-- "0..N" bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process : +name : bbf-yang:string-ascii64  {key} 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process : enabled : boolean   = true 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process : export-mode : identityref {export-mode}   = fallback 
class "destination" as bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination << (L, #FF7700) list>> 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process *-- "1..N" bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination : ordered-by : user
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination : +name : bbf-yang:string-ascii64  {key} 
class "exporter" as  bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter <<container>> 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination *-- "1" bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter : ipfix-version : uint16   = 10 
class "source" as  bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_source <<container>> 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter *-- "1" bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_source 
class "source-method" as bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_source_I_source_method <<choice>> 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_source .. bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_source_I_source_method : choice 
class "interface" as bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_source_I_source_method_I_interface_case <<case>>
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_source_I_source_method .. bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_source_I_source_method_I_interface_case  : choice source-method
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_source_I_source_method_I_interface_case : interface : if:interface-ref  
class "source-address" as bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_source_I_source_method_I_source_address_case <<case>>
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_source_I_source_method .. bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_source_I_source_method_I_source_address_case  : choice source-method
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_source_I_source_method_I_source_address_case : source-address : inet:host  
class "destination" as  bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_destination <<container>> 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter *-- "1" bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_destination 
class "destination-method" as bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_destination_I_destination_method <<choice>> 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_destination .. bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_destination_I_destination_method : choice 
class "destination-address" as bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_destination_I_destination_method_I_destination_address_case <<case>>
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_destination_I_destination_method .. bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_destination_I_destination_method_I_destination_address_case  : choice destination-method
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_destination_I_destination_method_I_destination_address_case : destination-address : inet:host  
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter : destination-port : inet:port-number  
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter : send-buffer-size : uint32   {bytes}
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter : rate-limit : uint32   {bytes per second}
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter : connection-timeout : uint32   {seconds}
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter : retry-schedule : uint32 [60..max]   = 60  {seconds}
class "security" as  bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_security <<container>> 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter *-- "1" bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_security 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_security : tlsc:tls-client-grouping {uses} 
class "transport-session" as  bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session <<container>> 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter *-- "1" bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session : source-address : inet:ip-address  
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session : destination-address : inet:ip-address  
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session : source-port : inet:port-number  
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session : destination-port : inet:port-number  
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session : status : transport-session-status  
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session : rate : yang:gauge32   {bytes per second}
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session : bytes : yang:counter64   {bytes}
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session : messages : yang:counter64   {IPFIX Messages}
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session : discarded-messages : yang:counter64   {IPFIX Messages}
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session : data-records : yang:counter64   {Data Records}
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session : templates : yang:counter32   {Templates}
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session : options-templates : yang:counter32   {Options Templates}
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session : start-time : yang:date-and-time  
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session : discontinuity-time : yang:date-and-time  
class "template" as bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template << (L, #FF7700) list>> 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session *-- "0..N" bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template : +name : bbf-yang:string-ascii64  {key} 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template : observation-domain-id : uint32  
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template : id : uint16 [256..65535]  
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template : set-id : uint16 [2..3 | 256..65535]  
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template : access-time : yang:date-and-time  
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template : data-records : yang:counter64  
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template : discontinuity-time : yang:date-and-time  
class "field" as bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template_I_field << (L, #FF7700) list>> 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template *-- "0..N" bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template_I_field 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template_I_field : +name : bbf-yang:string-ascii64  {key} 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template_I_field : ie-id : ie-id-type  
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template_I_field : ie-length : uint16   {octets}
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template_I_field : ie-enterprise-number : uint32  
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_destination_I_exporter_I_transport_session_I_template_I_field : is-scope : empty  
class "options" as bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_options << (L, #FF7700) list>> 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process *-- "0..N" bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_options 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_options : +name : bbf-yang:string-ascii64  {key} 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_options : options-type : identityref {options-type}   {mandatory}
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_options : options-timeout : uint32   {milliseconds}
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process : exporting-process-id : uint32   {Config : false}
class "template" as bbf_ipfix_data_export_I_ipfix_data_export_I_template << (L, #FF7700) list>> 
bbf_ipfix_data_export_I_ipfix_data_export *-- "0..N" bbf_ipfix_data_export_I_ipfix_data_export_I_template 
bbf_ipfix_data_export_I_ipfix_data_export_I_template : +name : bbf-yang:string-ascii64  {key} 
bbf_ipfix_data_export_I_ipfix_data_export_I_template : enabled : boolean   = true 
bbf_ipfix_data_export_I_ipfix_data_export_I_template : export-interval : uint32   {seconds}
bbf_ipfix_data_export_I_ipfix_data_export_I_template : observation-domain-id : uint32   = 0 
class "field-layout" as  bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout <<container>> 
bbf_ipfix_data_export_I_ipfix_data_export_I_template *-- "1" bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout 
class "field" as bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field << (L, #FF7700) list>> 
bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout *-- "1..N" bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field 
bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field : +name : bbf-yang:string-ascii64  {key} 
class "identifier" as bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field_I_identifier <<choice>> 
bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field .. bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field_I_identifier : choice 
class "ie-name" as bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field_I_identifier_I_ie_name_case <<case>>
bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field_I_identifier .. bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field_I_identifier_I_ie_name_case  : choice identifier
bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field_I_identifier_I_ie_name_case : ie-name : string  
class "ie-id" as bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field_I_identifier_I_ie_id_case <<case>>
bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field_I_identifier .. bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field_I_identifier_I_ie_id_case  : choice identifier
bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field_I_identifier_I_ie_id_case : ie-id : ie-id-type  
bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field : ie-length : uint16   {octets}
bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_field_layout_I_field : ie-enterprise-number : uint32   = 0 
bbf_ipfix_data_export_I_ipfix_data_export_I_template : exporting-process []: leafref : /ipfix-data-export/exporting-process/name  {if-feature : exporter}
class "resource-identifier" as bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_resource_identifier <<choice>> 
bbf_ipfix_data_export_I_ipfix_data_export_I_template .. bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_resource_identifier : choice 
class "resource-instance" as bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_resource_identifier_I_resource_instance_case <<case>>
bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_resource_identifier .. bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_resource_identifier_I_resource_instance_case  : choice resource-identifier
bbf_ipfix_data_export_I_ipfix_data_export_I_template_I_resource_identifier_I_resource_instance_case : resource-instance []: resource 
bbf_ipfix_data_export_I_ipfix_data_export_I_template : data-records : yang:counter64   {Data Records} {Config : false}
bbf_ipfix_data_export_I_ipfix_data_export_I_template : discontinuity-time : yang:date-and-time   {Config : false}
class "export-mode" as bbf_ipfix_de_export_mode_identity << (I,Silver) identity>> 
class "parallel" as bbf_ipfix_de_parallel_identity << (I,Silver) identity>> 
bbf_ipfix_de_export_mode_identity <|-- bbf_ipfix_de_parallel_identity 
class "load-balancing" as bbf_ipfix_de_load_balancing_identity << (I,Silver) identity>> 
bbf_ipfix_de_export_mode_identity <|-- bbf_ipfix_de_load_balancing_identity 
class "fallback" as bbf_ipfix_de_fallback_identity << (I,Silver) identity>> 
bbf_ipfix_de_export_mode_identity <|-- bbf_ipfix_de_fallback_identity 
class "options-type" as bbf_ipfix_de_options_type_identity << (I,Silver) identity>> 
class "exporting-reliability" as bbf_ipfix_de_exporting_reliability_identity << (I,Silver) identity>> 
bbf_ipfix_de_options_type_identity <|-- bbf_ipfix_de_exporting_reliability_identity 
class "reducing-redundancy" as bbf_ipfix_de_reducing_redundancy_identity << (I,Silver) identity>> 
bbf_ipfix_de_options_type_identity <|-- bbf_ipfix_de_reducing_redundancy_identity 
class "extended-type-information" as bbf_ipfix_de_extended_type_information_identity << (I,Silver) identity>> 
bbf_ipfix_de_options_type_identity <|-- bbf_ipfix_de_extended_type_information_identity 
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process-->bbf_ipfix_de_export_mode_identity : export-mode
bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process_I_options-->bbf_ipfix_de_options_type_identity : options-type
} 

bbf_yang_bbf_yang_types +-- bbf_ipfix_de_bbf_ipfix_data_export
inet_ietf_inet_types +-- bbf_ipfix_de_bbf_ipfix_data_export
yang_ietf_yang_types +-- bbf_ipfix_de_bbf_ipfix_data_export
if_ietf_interfaces +-- bbf_ipfix_de_bbf_ipfix_data_export
tlsc_ietf_tls_client +-- bbf_ipfix_de_bbf_ipfix_data_export
bbf_ipfix_data_export_I_ipfix_data_export_I_template-->"name"bbf_ipfix_data_export_I_ipfix_data_export_I_exporting_process: exporting-process
center footer
 <size:20> UML Generated : 2023-07-25 11:26 </size>
 endfooter 
@enduml 
